sentence = input("Enter your sentences : ")
print("Your Sentence is : "+sentence)
kata1 = input("Masukkan kata yang akan diganti : ")
kata2 = input("Masukkan kata yang pengganti : ")
print(sentence.replace(kata1,kata2))
